version: '3'
services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: students
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  etl:
    build: .
    depends_on:
      - db
    environment:
      DB_HOST: 'db'
      DB_PORT: 5432
      DB_USR: ${DB_USR}
      DB_PWD: ${DB_PWD}